name: daily-snapshots-risk-viz
on:
  schedule:
    - cron: "15 02 * * *"
  workflow_dispatch: {}

jobs:
  snapshots:
    runs-on: ubuntu-latest
    outputs:
      day: ${{ steps.date.outputs.day }}
    steps:
      # ... (без змін)

  risk:
    runs-on: ubuntu-latest
    needs: snapshots
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: pip install -r requirements.txt

      # >>> НОВЕ: створюємо директорію призначення
      - name: Prepare target dir
        run: mkdir -p data/${{ needs.snapshots.outputs.day }}

      # >>> НОВЕ: завантажуємо артефакт САМЕ в data/<day>/
      - name: Download snapshots artifact
        uses: actions/download-artifact@v4
        with:
          name: snapshots-${{ needs.snapshots.outputs.day }}
          path: data/${{ needs.snapshots.outputs.day }}

      # >>> НОВЕ: діагностика — покажемо, що всередині
      - name: List inputs
        run: |
          set -euxo pipefail
          ls -la
          ls -la data
          ls -la data/${{ needs.snapshots.outputs.day }} || true
          find data/${{ needs.snapshots.outputs.day }} -maxdepth 1 -type f -name '*_weights.csv' -print

      - name: Run batch risk
        env:
          DEBUG: "1"
          RB_PATH: data/${{ needs.snapshots.outputs.day }}
          RB_ALPHAS: "0.20,0.25,0.30,0.33"
          RB_LAMBDAS: "0,0.1,0.2,0.3"
          RB_TRIALS: "20000"
          RB_M_STRATEGY: "fraction:0.4"
        run: python risk_batch.py

      - name: Upload risk results (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: risk-${{ needs.snapshots.outputs.day }}
          path: data/${{ needs.snapshots.outputs.day }}/risk_results.csv

  viz:
    runs-on: ubuntu-latest
    needs: [snapshots, risk]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: pip install -r requirements.txt

      # >>> НОВЕ: забираємо готовий risk-артефакт у data/<day>/
      - name: Prepare target dir
        run: mkdir -p data/${{ needs.snapshots.outputs.day }}
      - name: Download risk artifact
        uses: actions/download-artifact@v4
        with:
          name: risk-${{ needs.snapshots.outputs.day }}
          path: data/${{ needs.snapshots.outputs.day }}

      # >>> НОВЕ: діагностика
      - name: List risk files
        run: |
          set -euxo pipefail
          ls -la data/${{ needs.snapshots.outputs.day }}
          head -n 5 data/${{ needs.snapshots.outputs.day }}/risk_results.csv || true

      - name: Build visualizations
        run: python viz_daily.py --path data/${{ needs.snapshots.outputs.day }}

      - name: Upload viz (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: viz-${{ needs.snapshots.outputs.day }}
          path: data/${{ needs.snapshots.outputs.day }}/viz/
